version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  modem:
    build:
      context: .
      dockerfile: modem/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - modem
      - redis
    environment:
      - REDIS_HOST=redis
