version: "3.8"

services:
  modem:
    build:
      context: .
      dockerfile: modem/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
