name: CI Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # TODO: FIXME (docker not working in pytest)
      # - name: Run tests
      #   run: make test

      - name: Run tests
        run: make validate-stack

      - name: Upload test logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: tests/logs
